[openai]
api_key = "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"

[youtube]
api_key= "AIzaSyCZvrlrMXE1jCPDLZ6NVMDe1uf_OXhYBkM"
