[openai]
api_key = "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"

[youtube]
api_key= "AIzaSyCZvrlrMXE1jCPDLZ6NVMDe1uf_OXhYBkM"
